tracktime: 120000
rewards:
  UNSPECIFIED: 100
  PLAYER: 1 10
  BAT: 0
  CHICKEN: 0 0.3
  COW: 0 0.5
  HORSE: -10 5
  MUSHROOM_COW: 2 5
  OCELOT: 5 100
  PIG: 2 5
  RABBIT: 2 5
  SHEEP: 2 5
  SNOWMAN: 2 5
  SQUID: 2 5
  VILLAGER_GOLEM: 2 5
  WOLF: 2 5
  VILLAGER: 2 5
  ENDERDRAGON: 2 5
  WITHERBOSS: 2 5
  BLAZE: 2 5
  CAVE_SPIDER: 2 5
  CREEPER: 2 5
  ENDERMAN: 2 5
  ENDERMITE: 2 5
  GHAST: 2 5
  GIANT: 2 5
  GUARDIAN: 2 5
  LAVA_SLIME: 2 5
  PIG_ZOMBIE: 2 5
  SILVERFISH: 2 5
  SKELETON: 2 5
  SLIME: 2 5
  SPIDER: 2 5
  WITCH: 2 5
  ZOMBIE: 2 5
  FISHING_HOOK: 2 5
  ARROW: 2 5
  SMALL_FIREBALL: 2 5
  FIREBALL: 2 5
  SNOWBALL: 2 5
  THROWN_ENDERPEARL: 2 5
  EYE_OF_ENDER_SIGNAL: 2 5
  THROWN_EGG: 2 5
  THROWN_POTION: 2 5
  THROWN_EXP_BOTTLE: 2 5
  FIREWORK: 2 5
  ITEM: 2 5
  MINECART: 2 5
  BOAT: 2 5
  PRIMED_TNT: 2 5
  FALLING_SAND: 2 5
  HANGING: 2 5
  ARMOR_STAND: 2 5
  XP_ORB: 2 5
  ENDER_CRYSTAL: 2 5